### ISSUE TITLE
Control verbosity in command line?

### ISSUE THREAD

**Issue by stumblingmages** [SimplrJS/scss-bundle#10]
PR #6 added some console logs that are a bit annoying in the gulp output.

Our build process is using an `execNodeTask` to run the `scss-bundle` CLI and the output clutters our build logs. So my question is this:

Is there a better way to leverage the bundler from gulp? Running `execNodeTask` doesn't seem gulp-ish.

Or could we silence the `console.log` statements on lines 61 and 79 of [bundle-cli.ts](https://github.com/SimplrJS/scss-bundle/blob/master/src/bundle-cli.ts). Perhaps enable them if a `--verbose` option were specified on the cli? Or `--silent` to suppress them?

**Comment by DovydasNavickas** [comment]
Sure, `--silent` seems to be the better solution here, because when using manually, use might not know that there is a `--verbose` mode and would miss the output.
And in your case, if you need the `--silent` option, you would come and look into readme for it.

**Comment by DovydasNavickas** [comment]
In PR #11, I've added the `verbosity` level and I also simplified `Config` building.
I though I've introduced a breaking-change by changing the `Contracts`, but only `bundle-cli` uses them and it is an enclosed, self-executing module, with only private functions, which makes it unlikely that anyone uses `Contracts` outside of its scope.

I've also published version `1.1.0` as `beta`, which you can try with:
```npm i scss-bundle@beta```
or
```yarn add scss-bundle@beta```

`verbosity` can now be set this way:
```
node dist\bundle-cli.js -e .\examples\partial-in-subdir\main.scss -d .\examples\output\partial-in-subdir.scss --verbosity Errors
```

Verbosity levels:
- `None` - does not emit any output and exits with a success or error code.
- `Error` - ouptuts only errors.
- `Verbose` - outputs all information, including a config used and tree of files being bundled.

Please test the new version and give your feedback.

**Comment by DovydasNavickas** [comment]
@stumblingmages any news? 😄

**Comment by stumblingmages** [comment]
The curse of our craft... things like to eat our time. I will give this a shot later today and report back.

**Comment by DovydasNavickas** [comment]
Awesome 👍 🎉

**Comment by stumblingmages** [comment]
It took a while but I couldn't test exactly what you've done. The Material2 team made a change to their stuff that obviated the need for this change. See this for details on how Material2 team silenced this verbosity https://github.com/angular/material2/commit/a225b77fc4cf8aaf8b3b2d3a364cf998b3813763

I think if that's an option on the execNodeTask that it will do the right thing but that scss-bundle should maybe use console.error(..) instead of console.log(..) when the conditions are actually an error.

There is probably still value in quieting the output when you use the scss-bundle on the command line.

**Comment by DovydasNavickas** [comment]
I guess I will publish the version then. There shouldn't be any breaking changes, therefore it's only gonna be easier to use.

**Comment by DovydasNavickas** [comment]
Done: https://github.com/SimplrJS/scss-bundle/commit/c9b5ff882a595dc0cfdf2e96df8c3f183da1f92a
