### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by lazarljubenovic** [SimplrJS/scss-bundle#3]
I keep getting this error no matter what I run. Is this a known issue or do I need to reproduce? I'm on Ubuntu 16.04.

**Comment by MartynasZilinskas** [comment]
Hey, it works in Windows environment. I will test it on Linux as soon as I can.

**Comment by lazarljubenovic** [comment]
Yeah I googled around and after opening the file in Atom and saving it as LF instead or CRLF it worked. So the problem are line endings in the file, but I'm not sure how to solve it so it works on all OS's.

**Comment by lazarljubenovic** [comment]
Looks like it didn't fix it. The problem appears to be [this line](https://github.com/QuatroCode/scss-bundle/blob/master/src/bundle-cli.ts#L1). After editing this file and saving it with LF line-endings, I've managed to run it... and although it says (with some warnings) that it's done, I don't see an output file. :/

**Comment by MartynasZilinskas** [comment]
Yep, I am still looking for the solution. Other packages like [screen-clear](https://github.com/Cycloware/npm-screen-clear) has/had the same problem.

Using directly works on my `Ubuntu 16.04.1`.

**Comment by lazarljubenovic** [comment]
So Typescript build step is the problem then. The generated JavaScript file has a `\r` thrown in by Windows (because you run the build process using it). Man, I can't believe that it's 2017 and we still have newline issues during development. :sob:

**Comment by lazarljubenovic** [comment]
I've installed the `v0.2.2` tag from GitHub through yarn, build the projec locally and calling `$ node node_modules/scss-bundle/dist/bundle-cli.js -e grassy.scss -d bundle.scss` runs correctly now. So at least we're 100% sure _what's_ the problem now. No idea how this is usually fixed. Does it work on Windows if you change `\r\n` to `\n` at least only on that problematic line? Maybe it could be a part of build step to "fix" the newline characters. 

Or if we can somehow "fix" the files _before_ they are run with a separate script?

**Comment by MartynasZilinskas** [comment]
If we change from `CRLF` (dos) to `LF` (unix), it should work on Windows.

I found that [Typescript compiler](https://www.typescriptlang.org/docs/handbook/compiler-options.html) has `--newLine` flag. I need to test it out if it works.

**Comment by lazarljubenovic** [comment]
It runs now, with `v0.2.3-beta` :+1:

**Comment by DovydasNavickas** [comment]
Fixed with https://github.com/QuatroCode/scss-bundle/commit/948e5af2571ef0e543822e28635cac4c233f4285

**Comment by lazarljubenovic** [comment]
Regression in `beta-1.0.2`, the files are again in CRLF.

**Comment by MartynasZilinskas** [comment]
`1.0.0-beta.3` works on Ubuntu.
