### ISSUE TITLE
Can we add include paths for resolving imports? e.g. --include-path in node-sass

### ISSUE THREAD

**Issue by vinayakpatil** [SimplrJS/scss-bundle#31]

**Comment by DovydasNavickas** [comment]
Of course, thought the team is super busy with hitting two deadlines at the moment, therefore we will not be able to do that ourselves fast :) Are you up for making a PR?

**Comment by vinayakpatil** [comment]
@DovydasNavickas https://github.com/SimplrJS/scss-bundle/pull/32

**Comment by vinayakpatil** [comment]
Closing as fixed now
