### ISSUE TITLE
Ignore @imports in comments

### ISSUE THREAD

**Issue by sumigoma** [SimplrJS/scss-bundle#33]
Currently scss-bundle appears to try to bundle all of my `@import` statements within comments, rather than ignoring them. I've only tried using it from the cli.
 
EDIT: Looking at the code, the commented import appears to only match if the line looks like 
```
//@import
```
with the `@import` immediately after `//`. The regex pattern should probably be made more flexible.

**Comment by DovydasNavickas** [comment]
@MartynasZilinskas already has a solution, tomorrow will make it into a proper PR. (it's 2am our time 😄)
