### ISSUE TITLE
Should we be able to bundle complex libraries?

### ISSUE THREAD

**Issue by ronnyek** [SimplrJS/scss-bundle#37]
Just a question, I tried to investigate this further by adding logging or somethign, but couldnt get it to work. 

Basically scss-bundle seems to work really pretty well... but there are cases where this library include a scss file in a chidl folder, and that scss includes something thats at the peer level as its container... so ..\design-tokens\somefile.scss.

File to import not found or unreadable: ../design-tokens/dist/salesforce-skin.map.

It's super easy for someone with a bit of time to reproduce.. .simply init and install @salesforce-ux/design-system, then create a styles.scss that has

```
@import "./node_modules/@salesforce-ux/design-system/scss/index.scss
```

I didn't know if this sort of thing SHOULD work for this library or not. Seems like webpack (I think that is what angular2+ uses) loads the scss files properly, so I dont know if its a problem with path resolution or what. 

Debug verbosity would be nice =)

**Comment by MartynasZilinskas** [comment]
> Should we be able to bundle complex libraries?

Yes, it can. What it does is scans files for imports and replaces them with imported file's contents. 

> I didn't know if this sort of thing SHOULD work for this library or not.

It should, because like I said it only checks for `imports` and tries to locate files. I think in this case it fails to resolve the location of that file.

> Debug verbosity would be nice =)

We have already an open issue for that https://github.com/SimplrJS/scss-bundle/issues/30. In case it's needed, we can work on it soon. Let's aim for next week to resolving this issue.

**Comment by DovydasNavickas** [comment]
Hey, @ronnyek. I'm looking at https://github.com/SimplrJS/scss-bundle/issues/39 and I'm thinking, whether it's a possible solution to this issue too?



If I understand correctly, then this import:
```sass
@import "./node_modules/@salesforce-ux/design-system/scss/index.scss"
```

Could be updated to:
```sass
@import "~/@salesforce-ux/design-system/scss/index.scss"
```

And this would solve both issues, wouldn't it?

Correct me if I'm wrong @alan-agius4.

**Comment by alan-agius4** [comment]
That is correct @DovydasNavickas
