### ISSUE TITLE
Feat: add support for tilde imports

### ISSUE THREAD

**Issue by alan-agius4** [SimplrJS/scss-bundle#39]
Add support for for tilde imports

This is already supported by webpack https://github.com/webpack-contrib/sass-loader and other node-sass importers like https://github.com/matthewdavidson/node-sass-tilde-importer

**Comment by andrei-ilyukovich** [comment]
+1 need this functionality as well

**Comment by nicolassigal** [comment]
+1 please

**Comment by daniel-mueller-me** [comment]
+1

**Comment by MartynasZilinskas** [comment]
We implemented this feature in `v2.2.0-beta.2` under `next` tag.
```
npm install scss-bundle@next -D
```

## Usage

Specifying project location is needed to work with tilde imports.

CLI (`-p`, `--project`):
```sh
scss-bundle -p . -e ./index.scss -d ./bundled.scss
```

Code sample:
```ts
import * as path from "path";
import { Bundler } from "scss-bundle";

(async () => {
    // Absolute project directory path.
    const projectDirectory = path.resolve(__dirname, "./cases/tilde-import");
    const bundler = new Bundler(undefined, projectDirectory);
    // Relative file path to project directory path.
    const result = await bundler.Bundle("./main.scss");
})();
```

**Comment by DovydasNavickas** [comment]
It would be nice to get some feedback 👍

**Comment by myang310** [comment]
I see that the #43 added Tilde support but it seems that it was not added when using the CLI though? Will that be added in an upcoming feature?

**Comment by DovydasNavickas** [comment]
@myang310, you might have missed that @MartynasZilinskas wrote how to use it with CLI:
>## Usage
>
>Specifying project location is needed to work with tilde imports.
>
>CLI (`-p`, `--project`):
>```sh
>scss-bundle -p . -e ./index.scss -d ./bundled.scss
>```

If you did not specify project, it won't work. Also, as @MartynasZilinskas wrote too, you have to install version on `next` tag:
>We implemented this feature in v2.2.0-beta.2 under next tag.
>
>```sh
>npm install scss-bundle@next -D
>```

**Comment by myang310** [comment]
@DovydasNavickas thanks a lot! yeah I didn't catch that, I was only looking at the master version's README

**Comment by pfeigl** [comment]
I think "." should be the default for project or better, it should have some default after all.
Just upgraded my project to your latest development state to test this and got the following error

```
(node:22112) UnhandledPromiseRejectionWarning: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:211:7)
    at BundleCli.getConfig (C:\Development\github\scss-bundle\dist\bundle-cli.js:33:36)
    at BundleCli.<anonymous> (C:\Development\github\scss-bundle\dist\bundle-cli.js:22:48)
    at Generator.next (<anonymous>)
    at C:\Development\github\scss-bundle\dist\bundle-cli.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Development\github\scss-bundle\dist\bundle-cli.js:4:12)
    at BundleCli.bundle (C:\Development\github\scss-bundle\dist\bundle-cli.js:21:16)
    at new BundleCli (C:\Development\github\scss-bundle\dist\bundle-cli.js:18:14)
(node:22112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Problem was, that "project" is `undefined` and thus `path.resolve(process.cwd(), argumentValues.project)` fails.
Even if it does not get a default value, it should bail out with a controlled error message like "Required parameter project not set".

**Comment by MartynasZilinskas** [comment]
I am closing this issue. If something doesn't work as expected, please open a new issue.
