### ISSUE TITLE
Doesn't load partials correctly when imported by omitting initial `_`

### ISSUE THREAD

**Issue by lazarljubenovic** [SimplrJS/scss-bundle#5]
My file has `@import 'global-to-chained.mixin';`, and the scripts fails (kinda silently, it still returns `0` and doesn't report error, just console.logs) with 

```
(node:7308) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/home/lazar/grassy/src/global-to-chained.mixin.scss'
(node:7308) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

That because such file indeed doesn't exist, it's prefixed with `_` as a partial: `_global-to-chained.mixin.scss`.

**Comment by DovydasNavickas** [comment]
If the file with the given name does not exist, we have to check with underscore prefix and append it instead. If none of those exist, there should be an error logged and error code returned.

**Comment by DovydasNavickas** [comment]
This is fixed with: https://github.com/SimplrJS/scss-bundle/pull/6

You can try it out with:
```yarn add scss-bundle@beta --dev```
Or:
```npm i scss-bundle@beta --save-dev```

Please report all of the error that you encounter 👏 😄

**Comment by lazarljubenovic** [comment]
```
_grassy.scss
├─┬ _global-to-chained.mixin.scss
│ ├── util/functional-programming.scss [NOT FOUND]
│ └── util/global-utils.scss [NOT FOUND]
├── _shorthand-to-expanded-syntax.scss
├─┬ _fixed-grid.scss
│ └── util/global-utils.scss [NOT FOUND]
├─┬ _grid.scss
│ ├── _shorthand-to-expanded-syntax.scss
│ ├── util/global-utils.scss [NOT FOUND]
│ └─┬ _parser.scss
│   └── util/global-utils.scss [NOT FOUND]
└─┬ _parser.scss
  └── util/global-utils.scss [NOT FOUND]
```

Looks like it fails to find files when the import path is in a subfolder; it was probably looking for `_util/file.scss` instead of `util/_file.scss`.

BTW, I'm glad my issue started an avalanche of making this module much better :+1:

**Comment by DovydasNavickas** [comment]
My bad 😄 Overoptimized abit.
https://github.com/SimplrJS/scss-bundle/commit/6da8e3f5519415d2b15f473053e5088a7d4b1a16 fixes
You can try `1.0.0-beta.2` on `scss-bundle@beta`

**Comment by lazarljubenovic** [comment]
Yup, it works properly now (although this time https://github.com/SimplrJS/scss-bundle/issues/3 is back :laughing:)
